export const LABELS = {
  shopName: '스타 타이',
  admin: '관리자',
  menu: ['타이관리', '아로마관리', '히알루론산 관리'],
  heroTitle: 'Premium Thai Massage',
  heroDescription: '프라이빗 힐링 공간',
  heroSubtitle: '프리미엄 타이 마사지 테라피',
  todayDateLabel: '오늘 날짜',
  capacityLabel: '인원',
  totalCapacityLabel: '전체 잔여 인원',
  timeRange: '🕐 10:00 ~ 23:30',
  adminMode: '관리자 모드',
  reservationSystemManagement: '예약 시스템 관리',
  maxCapacityLabel: '최대 인원 설정',
  autoApplyNotice: '모든 슬롯에 자동 적용됩니다',
  pendingTitle: '대기 중인 예약 신청',
  confirmButton: '✅ 확정',
  cancelButton: '❌ 취소',
  resetButton: '초기화',
  requestButton: '예약 신청 ✓',
  reservationPeopleLabel: '예약 인원',
  peopleLabel: '인원',
  massageTimeLabel: '마사지 시간',
  phoneNumberLabel: '전화번호',
  startTimeLabel: '시작 시간',
};
